apiVersion: v1
kind: Service
metadata:
  name: sonar
  namespace: sonarqube
spec:
  type: NodePort
  selector:
    app: sonarqube
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 31828 # you can choose a random open port between 30000-32767
