apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: ci-cd-pipeline-deployment
spec:
  selector:
    matchLabels:
      app: ci-cd-pipeline
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: ci-cd-pipeline
    spec:
      containers: 
        - name: ci-cd-pipeline
          image: akshat1304/CI-CD-Pipeline:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: ci-cd-pipeline-ssvc
spec:
  selector:
    app: ci-cd-pipeline
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 8080 
  type: LoadBalancer # type of the service.